sudo: false
dist: trusty
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
cache: pip
env:
  global:
    - CFLAGS="-coverage"
    - TRAVIS_TEST=true
install:
  - pip install --upgrade pip
  - pip install $(grep 'pytest' requirements.txt)
  - pip install coveralls coverage matplotlib==1.5.1
  - pip install -e .[]
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - py.test --cov=queueing_tool --cov-report term-missing
after_success:
  - coveralls
