language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
before_install:
  - echo 'deb http://downloads.skewed.de/apt/precise precise universe' | sudo tee -a /etc/apt/sources.list
  - echo 'deb-src http://downloads.skewed.de/apt/precise precise universe' | sudo tee -a /etc/apt/sources.list
  - sudo add-apt-repository ppa:boost-latest/ppa
  - sudo apt-get update -qq
install:
  # --allow-unauthenticated
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then sudo apt-get install -y python-graph-tool; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then sudo apt-get install -y python3-graph-tool; fi
  - pip install -r requirements.txt
  - pip install coveralls
script:
 - coverage run --source=queueing_tool setup.py test
after_success:
  - coveralls
