language: python
python:
  - 3.2
before_install:
  - echo 'deb http://downloads.skewed.de/apt/precise precise universe' | sudo tee -a /etc/apt/sources.list
  - curl http://pgp.skewed.de:11371/pks/lookup?op=get&search=0x612DEFB798507F25 | sudo apt-key add -
  - sudo add-apt-repository ppa:takluyver/python3 -y
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo add-apt-repository ppa:mapnik/boost -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -y install python3-setuptools python3-scipy python3-numpy
  #- sudo apt-get install -y libboost1.54-all-dev
  #- sudo apt-get -qq -f install libboost-iostreams1.54-dev libboost-python1.54-dev libboost-regex1.54-dev
  #- side apt-get -qq -f install libboost-graph1.54-dev libboost-system1.54-dev libboost-thread1.54-dev
  # --allow-unauthenticated
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then sudo apt-get install -y --allow-unauthenticated python-graph-tool; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then sudo apt-get install -y --allow-unauthenticated python3-graph-tool; fi
install:
  - pip install coveralls
script:
 - coverage run --source=queueing_tool setup.py test
after_success:
  - coveralls
