language: python
python:
  - 2.7
virtualenv:
  system_site_packages: true
before_install:
  - echo 'deb http://downloads.skewed.de/apt/trusty trusty universe' | sudo tee -a /etc/apt/sources.list
  - sudo add-apt-repository ppa:takluyver/python3 -y
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo add-apt-repository ppa:mapnik/boost -y
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y --allow-unauthenticated python-setuptools python-graph-tool
  - pip install -e .
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-package=queueing_tool -v
after_success:
  - coveralls
