language: python
python:
  - 2.7
  - "2.7_with_system_site_packages"
  - 3.2
  - "3.2_with_system_site_packages"
  - 3.3
  - 3.4
env:
  - CYTHON=true
  - CYTHON=false
before_install:
  - echo 'deb http://downloads.skewed.de/apt/precise precise universe' | sudo tee -a /etc/apt/sources.list
  - sudo add-apt-repository ppa:takluyver/python3 -y
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo add-apt-repository ppa:mapnik/boost -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy
  # --allow-unauthenticated
  # python3-numpy python3-numpy-dev python3-scipy
  #- if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then sudo apt-get install -y python-setuptools; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then sudo apt-get install -y --allow-unauthenticated python-numpy-dev python-setuptools python-graph-tool; fi
  #- if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then sudo apt-get install -y python3-setuptools; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then sudo apt-get install -y --allow-unauthenticated python3-numpy-dev python3-setuptools python3-graph-tool; fi
install:
  #- if [[ $TRAVIS_PYTHON_VERSION == 2* && $CYTHON == true ]]; then sudo apt-get install -y cython; fi
  #- if [[ $TRAVIS_PYTHON_VERSION == 3* && $CYTHON == true ]]; then sudo apt-get install -y cython3; fi
  - if [[ $CYTHON == true ]]; then pip install cython; fi
  - pip install -e .
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-package=queueing_tool
after_success:
  - coveralls
