language: python
python:
  - 2.7
  #- 3.2
  #- 3.3
  #- 3.4
env:
  - CYTHON=false
virtualenv:
  system_site_packages: true
before_install:
  - echo 'deb http://downloads.skewed.de/apt/precise precise universe' | sudo tee -a /etc/apt/sources.list
  - sudo add-apt-repository ppa:takluyver/python3 -y
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo add-apt-repository ppa:mapnik/boost -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then sudo apt-get install -y --allow-unauthenticated python-setuptools python-graph-tool; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then sudo apt-get install -y --allow-unauthenticated python3-setuptools python3-graph-tool; fi
  - if [[ $CYTHON == true ]]; then pip install cython; fi
  - pip install -e .
  #- python setup.py install
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-package=queueing_tool
after_success:
  - coveralls
