language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
env:
  - CYTHON=true
  - CYTHON=false
before_install:
  - echo 'deb http://downloads.skewed.de/apt/precise precise universe' | sudo tee -a /etc/apt/sources.list
  - sudo add-apt-repository ppa:takluyver/python3 -y
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo add-apt-repository ppa:mapnik/boost -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  # --allow-unauthenticated
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then sudo apt-get install -y python-numpy python-numpy-dev python-setuptools; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then sudo apt-get install -y --allow-unauthenticated python-graph-tool; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then sudo apt-get install -y python3-numpy python3-numpy-dev python3-setuptools; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then sudo apt-get install -y --allow-unauthenticated python3-graph-tool; fi
install:
  - if [[ $CYTHON == true ]]; then pip install scipy cython; fi
  - if [[ $CYTHON == false ]]; then pip install scipy; fi
  - pip install -e .
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-package=queueing_tool
after_success:
  - coveralls
